# fly.toml app configuration file generated for thing-lender on 2024-04-04T14:22:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thing-lender'
primary_region = 'ewr'

[[mounts]]
  source = 'pb_data'
  destination = '/app/pb_data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
